package com.rococo.springboot.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.rococo.springboot.model.PersonModel;
import com.rococo.springboot.repository.PersonRepository;

@Service
public class PersonServiceImpl implements PersonService {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private PersonRepository personRepository;

	@Override
	public PersonModel getPersonInfo(PersonModel personModel) {
		return personRepository.findById(personModel.getId()).get();
	}

	@Override
	public List<PersonModel> getAll() {
		List<PersonModel> list = new ArrayList<>();
		personRepository.findAll().iterator().forEachRemaining(list::add);
		return list;
	}

	/* (non-Javadoc)
	 * @see com.rococo.springboot.service.PersonService#registerPerson(com.rococo.springboot.model.PersonModel)
	 */
	@Override
	public void registerPerson(PersonModel personModel) {
		personRepository.save(personModel);
	}

}
